# RAGシステム設定ファイル

# 埋め込みに使用するモデル
embedding_model: text-embedding-3-small

# 回答生成に使用するモデル
completion_model: gpt-3.5-turbo

# チャンク分割設定
chunk_size: 500
chunk_overlap: 50

# 検索設定
top_k: 3

# ドキュメントディレクトリ
docs_dir: docs
